import { Routes, RouterModule } from '@angular/router';
import { InsideSeoPageComponent } from './inside-seo-page.component';

const routes: Routes = [
    {
        path: '',
        component: InsideSeoPageComponent,
        children: [
            { path: 'Class-wise-best-private-home-tutor', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Kindergarten', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Class1', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Class2', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Class3', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Class4', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Class5', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Class6', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Class7', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Class8', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Class9', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Class10', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Class_11_Arts', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Class_11_Commerce', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Class_11_Science', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Class_12_Arts', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Class_12_Commerce', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Class_12_Science', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Intermediate', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/LKG', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Nursery', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/PUC1', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/PUC2', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/UKG', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Class_Metric', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Class_SSLC', component: InsideSeoPageComponent },
            { path: 'Class-wise-best-private-home-tutor/Engineering', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/Account', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/Biology', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/Business_Studies', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/Chemistry', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/English', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/French', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/Geography', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/German', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/Hindi', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/History', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/Kannada', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/Mathematics', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/Maths', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/Physics', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/Sanskrit', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/Science', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/Social_Science', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/Spoken_English', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/Spoken_Hindi', component: InsideSeoPageComponent },
            { path: 'Subjects-wise-best-private-home-tutor/Spoken_Kannada', component: InsideSeoPageComponent },
            { path: 'Syllabus-wise-best-private-home-tutor', component: InsideSeoPageComponent },
            { path: 'Syllabus-wise-best-private-home-tutor/CBSE', component: InsideSeoPageComponent },
            { path: 'Syllabus-wise-best-private-home-tutor/IB_IGCSE', component: InsideSeoPageComponent },
            { path: 'Syllabus-wise-best-private-home-tutor/ICSE', component: InsideSeoPageComponent },
            { path: 'Syllabus-wise-best-private-home-tutor/State_Board', component: InsideSeoPageComponent },
            { path: '', redirectTo: 'home', pathMatch: 'full' },
            { path: '**', redirectTo: 'home' }
        ]
    }
];

export const routing = RouterModule.forChild(routes);